#!/bin/bash -e
# regenerate anible-semaphore cookie_hash, cookie_encryption & mysql password

. /etc/default/inithooks

rand() { head -c 32 /dev/urandom | base64; }

updateconf() {
    sed -i "\| *\"$1\"| s|:.*|: \"$2\",|" $CONF
}

CONF=/etc/semaphore/config.json

updateconf cookie_hash $(rand)
updateconf cookie_encryption $(rand)

PASSWORD=$(mcookie)
updateconf pass $PASSWORD
$INITHOOKS_PATH/bin/mysqlconf.py --user=semaphore --pass="$PASSWORD"
