#!/bin/bash -e
# add ansible ssh key to root's authorized_keys
# allows ansible to login as root without a password
# Also add keypair to example TurnKey Semaphore project

APP_USER=ansible

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

# make sure the .ssh directory exists
if [[ $SUDOADMIN == "true" ]]; then
    ADMIN_HOME=/home/admin
else
    ADMIN_HOME=/root
fi
mkdir -p $ADMIN_HOME/.ssh
PUB_KEY=$(cat /home/$APP_USER/.ssh/id_rsa.pub)
PRV_KEY=$(cat /home/$APP_USER/.ssh/id_rsa)
echo $PUB_KEY >> $ADMIN_HOME/.ssh/authorized_keys

mysql -e " \
    INSERT INTO semaphore.access_key VALUES (1,'Ansible SSH key','ssh',2,'$PUB_KEY','$PRV_KEY',0);" \
        2>/dev/null \
        || echo "A SSH key is already registered, skipping" >&2
